server:
  port: 8080

spring:
  application:
    name: welldata-ephemeral-fhir-service

welldata:
  testdata:
    path: classpath:testdata
    enabled: true  # Set to false when using Solid pod for data storage
  ig:
    url: https://github.com/GIDSOpenStandaarden/welldata-implementation-guide/releases/download/v0.1.1/welldata-0.1.1.tgz
  solid:
    enabled: false  # Set to true to enable Solid pod integration
    # Pod URL is automatically derived from the user's WebID (sub claim in JWT)
    fhir-container-path: /weare/fhir

logging:
  level:
    nl.gidsopenstandaarden.welldata: DEBUG
    ca.uhn.fhir: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
